[package]
name = "make_fself"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.7.3"
clap = { version = "4.4.6", features = ["derive"] }
sha2 = "0.10"
anyhow = "1.0"
byteorder = "1.5.0"
