[package]
name = "make_fself"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
hmac = "0.12.1"
clap = { version = "4.4.6", features = ["derive"] }
elf = "0.7.3"
